### ISSUE TITLE
History's delete button!

### ISSUE THREAD

**Issue by sujan-ss** [anirudhadhu/Collab-Codes#11]
Unable to delete the calculated taxes in the history.
![image](https://github.com/anirudhadhu/Collab-Codes/assets/108802444/12504eb7-97a2-41c0-9da8-3c4d9b9fd954)

@anirudhadhu

**Comment by anirudhadhu** [comment]
Everything looks great here, please redo the task and see the console if there is any error if any error occurs kindly notify. Thankyou
