### ISSUE TITLE
Button CSS

### ISSUE THREAD

**Issue by sujan-ss** [anirudhadhu/Collab-Codes#13]
Need to change the button's CSS.

![image](https://github.com/anirudhadhu/Collab-Codes/assets/108802444/3dc1313c-3a9f-460a-b2e7-360089ce00ca)

@anirudhadhu

**Comment by anirudhadhu** [comment]
Done
![image](https://github.com/anirudhadhu/Collab-Codes/assets/108577073/e003d365-d9e9-4ee2-93e2-effeb1447bc2)
![image](https://github.com/anirudhadhu/Collab-Codes/assets/108577073/8a9d764e-3223-451d-8fab-a55675862df7)
