### ISSUE TITLE
Back option!

### ISSUE THREAD

**Issue by sujan-ss** [anirudhadhu/Collab-Codes#15]
The back option is not working on the About Us page.

![image](https://github.com/anirudhadhu/Collab-Codes/assets/108802444/f1d673a9-047d-42e5-8f1c-e8ea963e5c4a)

**Comment by anirudhadhu** [comment]
Noted ! It's solved now please verify.

![image](https://github.com/anirudhadhu/Collab-Codes/assets/108577073/750d354a-a477-42ef-8f16-c2e8b6e506e9)
